/*
COVID 19 DATA EXPLORATION 
SKILLS USED: JOINS, CTE'S, TEMP TABLES, WINDOWS FUNCTIONS, AGGREGATE FUNCTIONS, CREATING VIEWS, CONVERTING DATA TYPES
*/

SELECT * FROM  [PORTFOLIO PROJECT].DBO.DEATHS

--SELECT DATA THAT WE ARE GOING TO BE STARTING WITH

SELECT LOCATION, DATE, TOTAL_CASES, NEW_CASES, TOTAL_DEATHS, POPULATION
FROM [PORTFOLIO PROJECT].DBO.DEATHS
WHERE CONTINENT IS NOT NULL 
ORDER BY 1,2

-- TOTAL CASES VS TOTAL DEATHS
-- SHOWS LIKELIHOOD OF DYING IF YOU CONTRACT COVID IN YOUR COUNTRY
SELECT LOCATION, DATE, TOTAL_CASES,TOTAL_DEATHS, (TOTAL_DEATHS/TOTAL_CASES)*100 AS DEATHPERCENTAGE
FROM [PORTFOLIO PROJECT].DBO.DEATHS
WHERE CONTINENT IS NOT NULL 
ORDER BY 1,2

--TOTAL CASES VS POPULATION
-- SHOWS WHAT PERCENTAGE OF POPULATION INFECTED WITH COVID
SELECT LOCATION, DATE, POPULATION, TOTAL_CASES,  (TOTAL_CASES/POPULATION)*100 AS PERCENTPOPULATIONINFECTED
FROM [PORTFOLIO PROJECT].DBO.DEATHS
ORDER BY 1,2

--COUNTRIES WITH HIGHEST INFECTION RATE COMPARED TO POPULATION

SELECT LOCATION, POPULATION, MAX(TOTAL_CASES) AS HIGHESTINFECTIONCOUNT,  MAX((TOTAL_CASES/POPULATION))*100 AS PERCENTPOPULATIONINFECTED
FROM [PORTFOLIO PROJECT].DBO.DEATHS
GROUP BY LOCATION, POPULATION
ORDER BY PERCENTPOPULATIONINFECTED DESC

-- COUNTRIES WITH HIGHEST DEATH COUNT PER POPULATION

SELECT LOCATION, MAX(CAST(TOTAL_DEATHS AS INT)) AS TOTALDEATHCOUNT
FROM [PORTFOLIO PROJECT].DBO.DEATHS
WHERE CONTINENT IS NOT NULL 
GROUP BY LOCATION
ORDER BY 2 DESC

-- BREAKING THINGS DOWN BY CONTINENT

-- SHOWING CONTINTENTS WITH THE HIGHEST DEATH COUNT PER POPULATION

SELECT CONTINENT, MAX(CAST(TOTAL_DEATHS AS INT)) AS TOTALDEATHCOUNT
FROM [PORTFOLIO PROJECT].DBO.DEATHS
WHERE CONTINENT IS NOT NULL 
GROUP BY CONTINENT
ORDER BY TOTALDEATHCOUNT DESC

-- GLOBAL NUMBERS

SELECT SUM(NEW_CASES) AS TOTAL_CASES, SUM(CAST(NEW_DEATHS AS INT)) AS TOTAL_DEATHS, SUM(CAST(NEW_DEATHS AS INT))/SUM(NEW_CASES)*100 AS DEATHPERCENTAGE
FROM [PORTFOLIO PROJECT].DBO.DEATHS
WHERE CONTINENT IS NOT NULL 
ORDER BY 1,2

-- TOTAL POPULATION VS VACCINATIONS
-- SHOWS PERCENTAGE OF POPULATION THAT HAS RECIEVED AT LEAST ONE COVID VACCINE

SELECT D.CONTINENT, D.LOCATION, D.DATE, D.POPULATION, V.NEW_VACCINATIONS
,SUM(CONVERT(INT,V.NEW_VACCINATIONS)) OVER (PARTITION BY D.LOCATION ORDER BY D.LOCATION, D.DATE) AS ROLLINGPEOPLEVACCINATED
--, (ROLLINGPEOPLEVACCINATED/POPULATION)*100
FROM [PORTFOLIO PROJECT].DBO.DEATHS as D
JOIN [PORTFOLIO PROJECT].DBO.VACCINATIONS as V
	ON D.LOCATION = V.LOCATION
	AND D.DATE = V.DATE
WHERE D.CONTINENT IS NOT NULL 
ORDER BY 2,3

-- USING CTE TO PERFORM CALCULATION ON PARTITION BY IN PREVIOUS QUERY

WITH POPVSVAC (CONTINENT, LOCATION, DATE, POPULATION, NEW_VACCINATIONS, ROLLINGPEOPLEVACCINATED)
AS
(
SELECT D.CONTINENT, D.LOCATION, D.DATE, D.POPULATION, V.NEW_VACCINATIONS
, SUM(CONVERT(INT,V.NEW_VACCINATIONS)) OVER (PARTITION BY D.LOCATION ORDER BY D.LOCATION, D.DATE) AS ROLLINGPEOPLEVACCINATED
--, (ROLLINGPEOPLEVACCINATED/POPULATION)*100
FROM [PORTFOLIO PROJECT].DBO.DEATHS as D
JOIN [PORTFOLIO PROJECT].DBO.VACCINATIONS as V
	ON D.LOCATION = V.LOCATION
	AND D.DATE = V.DATE
WHERE D.CONTINENT IS NOT NULL  
--ORDER BY 2,3
)
SELECT *, (ROLLINGPEOPLEVACCINATED/POPULATION)*100
FROM POPVSVAC 



-- USING TEMP TABLE TO PERFORM CALCULATION ON PARTITION BY IN PREVIOUS QUERY

DROP TABLE IF EXISTS #PERCENTPOPULATIONVACCINATED
CREATE TABLE #PERCENTPOPULATIONVACCINATED
(
CONTINENT NVARCHAR(255),
LOCATION NVARCHAR(255),
DATE DATETIME,
POPULATION NUMERIC,
NEW_VACCINATIONS NUMERIC,
ROLLINGPEOPLEVACCINATED NUMERIC
)

INSERT INTO #PERCENTPOPULATIONVACCINATED
SELECT D.CONTINENT, D.LOCATION, D.DATE, D.POPULATION, V.NEW_VACCINATIONS
, SUM(CONVERT(INT,V.NEW_VACCINATIONS)) OVER (PARTITION BY D.LOCATION ORDER BY D.LOCATION, D.DATE) AS ROLLINGPEOPLEVACCINATED
--, (ROLLINGPEOPLEVACCINATED/POPULATION)*100
FROM [PORTFOLIO PROJECT].DBO.DEATHS D
JOIN [PORTFOLIO PROJECT].DBO.VACCINATIONS V
	ON D.LOCATION = V.LOCATION
	AND D.DATE = V.DATE
WHERE D.CONTINENT IS NOT NULL 
--ORDER BY 2,3

SELECT *, (ROLLINGPEOPLEVACCINATED/POPULATION)*100
FROM #PERCENTPOPULATIONVACCINATED




-- CREATING VIEW TO STORE DATA FOR LATER VISUALIZATIONS


CREATE VIEW PERCPOPULATIONVACCINATED AS
SELECT D.CONTINENT, D.LOCATION, D.DATE, D.POPULATION, V.NEW_VACCINATIONS
, SUM(CONVERT(INT,V.NEW_VACCINATIONS)) OVER (PARTITION BY D.LOCATION ORDER BY D.LOCATION, D.DATE) AS ROLLINGPEOPLEVACCINATED
--, (ROLLINGPEOPLEVACCINATED/POPULATION)*100
FROM [PORTFOLIO PROJECT].DBO.DEATHS D
JOIN [PORTFOLIO PROJECT].DBO.VACCINATIONS V
	ON D.LOCATION = V.LOCATION
	AND D.DATE = V.DATE
WHERE D.CONTINENT IS NOT NULL

DROP VIEW [PERCPOPULATIONVACCINATED]



